###################################
#                                 #
#            WildCore             #
#                                 #
###################################
ip-adress: "localhost"
user: "root"
password: ""
database: ""