###################################
#                                 #
#            WildCore             #
#                                 #
###################################
ip-adress: "mysql.hostify.cz"
user: "db_40366_wildcraft"
password: "gOwZLxhofDyJN9Rc"
database: "db_40366_wildcraft"


no-perms: "{#FF0000>}&lWC{#E4A025<} §8§l» §cNeznámy príkaz"
serverWarpWrongUsage: "{#FF0000>}&lWC{#E4A025<} §8§l» §cZlí argumenty! Použi /setServerWarp <jméno>"